In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# --- Toy Dataset (Same as the manual example) ---
# Features (Columns) represent word counts for:
# [Game, Score, Data, Algorithm, Win]
# Class 0 = Sports, Class 1 = Tech

X = np.array([
    [3, 2, 0, 0, 1], # Doc 1: Sports
    [2, 3, 0, 0, 0], # Doc 2: Sports
    [0, 0, 4, 1, 0], # Doc 3: Tech
    [0, 0, 5, 2, 0], # Doc 4: Tech
    [1, 1, 1, 1, 1]  # Doc 5: Sports (Mixed)
])
y = np.array([0, 0, 1, 1, 0])

# New Data to Classify: [Game: 1, Score: 0, Data: 1, Algorithm: 1, Win: 0]
X_new = np.array([
    [1, 0, 1, 1, 0]
])

# 1. Initialize the Multinomial Naive Bayes Model
# The 'alpha' parameter defaults to 1.0, implementing Laplace (Add-1) smoothing.
nb_model = MultinomialNB(alpha=1.0)

# 2. Train the model (Fit)
# In real scenarios, you would split the data into training and testing sets,
# but for this small example, we train on the entire set.
nb_model.fit(X, y)

# 3. Make predictions on the new sample
prediction = nb_model.predict(X_new)

# 4. Get probability estimates (A key output of NB)
# This returns the log probabilities P(C|X) for each class.
log_proba = nb_model.predict_log_proba(X_new)

# 5. Get actual probability estimates
proba = nb_model.predict_proba(X_new)


print("--- Scikit-learn Multinomial Naive Bayes Results ---")
print(f"Test Sample: {X_new[0]}")
print(f"Predicted Class (0=Sports, 1=Tech): {prediction[0]}")

print("\n--- Model Output Details ---")
print("Log Probability for each class (0, 1):")
# The class with the highest (least negative) log probability is the prediction
print(log_proba[0])

print("Actual Probability for each class (0, 1):")
# The class with the highest probability is the prediction
print(proba[0])

# --- Optional: Check Model's Learned Parameters ---
print("\n--- Learned Parameters ---")
# log_prior_: log(P(C)) - log of the prior probability for each class
print(f"Log Class Priors (log(P(C))): {nb_model.class_log_prior_}")
# feature_log_prob_: log(P(x_i|C)) - log of the likelihood for each feature given the class
print("Log Likelihoods for each Feature (log(P(x_i|C))):")
print(f"Class 0 (Sports): {nb_model.feature_log_prob_[0]}")
print(f"Class 1 (Tech):   {nb_model.feature_log_prob_[1]}")
print("--------------------------------------------------")

--- Scikit-learn Multinomial Naive Bayes Results ---
Test Sample: [1 0 1 1 0]
Predicted Class (0=Sports, 1=Tech): 1

--- Model Output Details ---
Log Probability for each class (0, 1):
[-1.02791694 -0.44277983]
Actual Probability for each class (0, 1):
[0.3577514 0.6422486]

--- Learned Parameters ---
Log Class Priors (log(P(C))): [-0.51082562 -0.91629073]
Log Likelihoods for each Feature (log(P(x_i|C))):
Class 0 (Sports): [-1.09861229 -1.09861229 -2.35137526 -2.35137526 -1.94591015]
Class 1 (Tech):   [-2.83321334 -2.83321334 -0.53062825 -1.44691898 -2.83321334]
--------------------------------------------------


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
# We import GaussianNB instead of MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# --- Toy Dataset (Now treated as continuous numerical features) ---
# GaussianNB assumes the values in these columns (features) are continuous
# and follow a normal distribution within each class.
X = np.array([
    [3, 2, 0, 0, 1], # Doc 1: Sports
    [2, 3, 0, 0, 0], # Doc 2: Sports
    [0, 0, 4, 1, 0], # Doc 3: Tech
    [0, 0, 5, 2, 0], # Doc 4: Tech
    [1, 1, 1, 1, 1]  # Doc 5: Sports (Mixed)
])
y = np.array([0, 0, 1, 1, 0])

# New Data to Classify:
X_new = np.array([
    [1, 0, 1, 1, 0]
])

# 1. Initialize the Gaussian Naive Bayes Model
# GNB does not require an 'alpha' smoothing parameter like MNB
nb_model = GaussianNB()

# 2. Train the model (Fit)
nb_model.fit(X, y)

# 3. Make predictions on the new sample
prediction = nb_model.predict(X_new)

# 4. Get probability estimates
# This returns the log probabilities P(C|X) for each class, calculated using the
# Gaussian Probability Density Function (PDF).
log_proba = nb_model.predict_log_proba(X_new)

# 5. Get actual probability estimates
proba = nb_model.predict_proba(X_new)


print("--- Scikit-learn Gaussian Naive Bayes Results ---")
print(f"Test Sample: {X_new[0]}")
print(f"Predicted Class (0=Sports, 1=Tech): {prediction[0]}")

print("\n--- Model Output Details ---")
print("Log Probability for each class (0, 1):")
print(log_proba[0])

print("Actual Probability for each class (0, 1):")
print(proba[0])

# --- Optional: Check Model's Learned Parameters ---
print("\n--- Learned Parameters (Mean and Variance) ---")
# class_prior_: P(C) - prior probability for each class
print(f"Class Priors (P(C)): {nb_model.class_prior_}")

# theta_: Mean (μ) of each feature for each class
# GNB uses these means and variances to calculate likelihoods P(x_i|C) using the Gaussian PDF.
print("\nClass Means (theta_): Mean of each feature in each class")
print(f"Class 0 (Sports) Means: {nb_model.theta_[0]}")
print(f"Class 1 (Tech) Means: {nb_model.theta_[1]}")

# var_: Variance (σ²) of each feature for each class
print("\nClass Variances (var_): Variance of each feature in each class")
print(f"Class 0 (Sports) Variances: {nb_model.var_[0]}")
print(f"Class 1 (Tech) Variances: {nb_model.var_[1]}")
print("--------------------------------------------------")

--- Scikit-learn Gaussian Naive Bayes Results ---
Test Sample: [1 0 1 1 0]
Predicted Class (0=Sports, 1=Tech): 0

--- Model Output Details ---
Log Probability for each class (0, 1):
[ 0.00000000e+00 -1.13636355e+08]
Actual Probability for each class (0, 1):
[1. 0.]

--- Learned Parameters (Mean and Variance) ---
Class Priors (P(C)): [0.6 0.4]

Class Means (theta_): Mean of each feature in each class
Class 0 (Sports) Means: [2.         2.         0.33333333 0.33333333 0.66666667]
Class 1 (Tech) Means: [0.  0.  4.5 1.5 0. ]

Class Variances (var_): Variance of each feature in each class
Class 0 (Sports) Variances: [0.66666667 0.66666667 0.22222223 0.22222223 0.22222223]
Class 1 (Tech) Variances: [4.40000000e-09 4.40000000e-09 2.50000004e-01 2.50000004e-01
 4.40000000e-09]
--------------------------------------------------


Bernoulli NB is specifically designed for features that are binary (0 or 1), representing the presence or absence of an event (like a word existing in a document). Since our existing toy data is a count matrix, the most important step is to binarize it before fitting the BNB model.

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
# We import BernoulliNB, which is ideal for binary (0 or 1) features
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# --- Toy Dataset (Original Count Data) ---
# Features (Columns) represent word counts for:
# [Game, Score, Data, Algorithm, Win]
# Class 0 = Sports, Class 1 = Tech

X_counts = np.array([
    [3, 2, 0, 0, 1], # Doc 1: Sports
    [2, 3, 0, 0, 0], # Doc 2: Sports
    [0, 0, 4, 1, 0], # Doc 3: Tech
    [0, 0, 5, 2, 0], # Doc 4: Tech
    [1, 1, 1, 1, 1]  # Doc 5: Sports (Mixed)
])
y = np.array([0, 0, 1, 1, 0])

# New Data to Classify:
X_new_counts = np.array([
    [1, 0, 1, 1, 0]
])

# --- CRITICAL STEP for BernoulliNB: Binarization ---
# BernoulliNB models presence or absence (1 or 0).
# We convert the count data to binary data where any count > 0 becomes 1.
X = (X_counts > 0).astype(int)
X_new = (X_new_counts > 0).astype(int)

print("--- Data Used for BernoulliNB (Presence/Absence) ---")
print("Original X (Counts):\n", X_counts)
print("Binarized X (Presence/Absence):\n", X)
print("---------------------------------------------------\n")

# 1. Initialize the Bernoulli Naive Bayes Model
# The 'alpha' parameter (default=1.0) implements Laplace smoothing.
# 'binarize=None' is used because we pre-binarized the data.
nb_model = BernoulliNB(alpha=1.0)

# 2. Train the model (Fit)
nb_model.fit(X, y)

# 3. Make predictions on the new sample
prediction = nb_model.predict(X_new)

# 4. Get probability estimates
log_proba = nb_model.predict_log_proba(X_new)

# 5. Get actual probability estimates
proba = nb_model.predict_proba(X_new)


print("--- Scikit-learn Bernoulli Naive Bayes Results ---")
print(f"Test Sample (Presence/Absence): {X_new[0]}")
print(f"Predicted Class (0=Sports, 1=Tech): {prediction[0]}")

print("\n--- Model Output Details ---")
print("Log Probability for each class (0, 1):")
print(log_proba[0])

print("Actual Probability for each class (0, 1):")
print(proba[0])

# --- Optional: Check Model's Learned Parameters ---
print("\n--- Learned Parameters (P(feature|Class)) ---")
# class_log_prior_: log(P(C)) - log of the prior probability for each class
print(f"Log Class Priors (log(P(C))): {nb_model.class_log_prior_}")
# feature_log_prob_: log(P(x_i|C)) - log of the likelihood P(feature present|C)
# BernoulliNB models P(x_i|C) and P(not x_i|C). This attribute holds P(x_i=1|C).
print("Log Likelihoods P(feature=1|C) for each Feature:")
print(f"Class 0 (Sports): {nb_model.feature_log_prob_[0]}")
print(f"Class 1 (Tech):   {nb_model.feature_log_prob_[1]}")
print("--------------------------------------------------")

--- Data Used for BernoulliNB (Presence/Absence) ---
Original X (Counts):
 [[3 2 0 0 1]
 [2 3 0 0 0]
 [0 0 4 1 0]
 [0 0 5 2 0]
 [1 1 1 1 1]]
Binarized X (Presence/Absence):
 [[1 1 0 0 1]
 [1 1 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [1 1 1 1 1]]
---------------------------------------------------

--- Scikit-learn Bernoulli Naive Bayes Results ---
Test Sample (Presence/Absence): [1 0 1 1 0]
Predicted Class (0=Sports, 1=Tech): 1

--- Model Output Details ---
Log Probability for each class (0, 1):
[-1.81642628 -0.17746038]
Actual Probability for each class (0, 1):
[0.16260582 0.83739418]

--- Learned Parameters (P(feature|Class)) ---
Log Class Priors (log(P(C))): [-0.51082562 -0.91629073]
Log Likelihoods P(feature=1|C) for each Feature:
Class 0 (Sports): [-0.22314355 -0.22314355 -0.91629073 -0.91629073 -0.51082562]
Class 1 (Tech):   [-1.38629436 -1.38629436 -0.28768207 -0.28768207 -1.38629436]
--------------------------------------------------
